import { PropsWithChildren } from "react";
import IntroSection from "../modules/IntroSection";
import BaseSection from "../modules/BaseSection";
import Footer from "../modules/Footer";
import Head from "next/head";

const Layout = ({ children }: PropsWithChildren<any>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseSection>
        <IntroSection
          introText="Test"
          imagePath="/images/wiesbachaue.jpg"
        ></IntroSection>
      </BaseSection>

      <main>{children}</main>

      <Footer />
    </>
  );
};

export default Layout;
